# Generated by Django 5.1.3 on 2025-06-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wardrobe", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="designerpost",
            name="caption",
        ),
        migrations.RemoveField(
            model_name="designerpost",
            name="outfit_image",
        ),
        migrations.AddField(
            model_name="designerpost",
            name="content",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="designerpost",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="designer_posts/"),
        ),
        migrations.AlterField(
            model_name="item",
            name="brand",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="size",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
